import { id, getInitials } from "./utils"
import type {
  AppSettings,
  Contact,
  Conversation,
  KnowledgeBaseArticle,
  Mailbox,
  Message,
  SavedReply,
  Tag,
  User,
  Workflow,
} from "../types"

const now = new Date().toISOString()
const dayAgo = new Date(Date.now() - 86400000).toISOString()
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString()
const threeDaysAgo = new Date(Date.now() - 259200000).toISOString()
const fourDaysAgo = new Date(Date.now() - 345600000).toISOString()

export const mockUsers: User[] = [
  {
    id: "u_alex",
    name: "Alex Morgan",
    email: "alex@isotopiq.io",
    role: "admin",
    status: "active",
    timezone: "America/Los_Angeles",
    permissions: ["*"],
    initials: "AM",
  },
  {
    id: "u_sarah",
    name: "Sarah Chen",
    email: "sarah.chen@isotopiq.io",
    role: "agent",
    status: "active",
    timezone: "America/Los_Angeles",
    permissions: ["conversations", "contacts", "reports"],
    initials: "SC",
  },
  {
    id: "u_priya",
    name: "Priya Nair",
    email: "priya@isotopiq.io",
    role: "agent",
    status: "away",
    timezone: "Europe/London",
    permissions: ["conversations", "contacts"],
    initials: "PN",
  },
  {
    id: "u_marcus",
    name: "Marcus Rivera",
    email: "mrivera@neuralstack.dev",
    role: "customer",
    status: "active",
    timezone: "America/New_York",
    permissions: [],
    initials: "MR",
  },
]

export const mockMailboxes: Mailbox[] = [
  {
    id: "mb_support",
    name: "Support",
    email: "support@isotopiq.io",
    color: "#2896E8",
    userIds: ["u_alex", "u_sarah", "u_priya"],
    signature: "— Isotopiq Support",
  },
  {
    id: "mb_sales",
    name: "Sales",
    email: "sales@isotopiq.io",
    color: "#10B981",
    userIds: ["u_alex", "u_sarah"],
  },
  {
    id: "mb_billing",
    name: "Billing",
    email: "billing@isotopiq.io",
    color: "#F59E0B",
    userIds: ["u_alex"],
  },
]

export const mockContacts: Contact[] = [
  {
    id: "c_sarah",
    name: "Sarah Chen",
    email: "sarah.chen@isotopiq.io",
    company: "Isotopiq",
    notes: [],
    customFields: {},
    createdAt: twoDaysAgo,
  },
  {
    id: "c_marcus",
    name: "Marcus Rivera",
    email: "mrivera@neuralstack.dev",
    company: "Neural Stack",
    notes: [],
    customFields: { deal_size: "250k" },
    createdAt: threeDaysAgo,
  },
  {
    id: "c_stripe",
    name: "Stripe Billing",
    email: "receipt@stripe.com",
    company: "Stripe",
    notes: [],
    customFields: {},
    createdAt: fourDaysAgo,
  },
]

export const mockTags: Tag[] = [
  { id: "t_important", name: "Important", color: "#EF4444" },
  { id: "t_finance", name: "Finance", color: "#F59E0B" },
  { id: "t_design", name: "Design", color: "#8B5CF6" },
  { id: "t_engineering", name: "Engineering", color: "#10B981" },
  { id: "t_partnership", name: "Partnership", color: "#2896E8" },
]

export const mockSavedReplies: SavedReply[] = [
  {
    id: "sr_1",
    name: "Welcome",
    subject: "Welcome to Isotopiq",
    body: "<p>Hi there,</p><p>Thanks for reaching out. We are happy to help.</p>",
  },
  {
    id: "sr_2",
    name: "Status update",
    subject: "Re: {{ticket.subject}}",
    body: "<p>Hi,</p><p>We are still looking into this and will update you shortly.</p>",
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: "wf_1",
    name: "Auto-assign sales",
    active: true,
    conditions: "mailbox == sales",
    actions: "assign u_sarah; tag partnership",
  },
]

export const mockArticles: KnowledgeBaseArticle[] = [
  {
    id: "kb_1",
    title: "Getting Started",
    slug: "getting-started",
    category: "General",
    body: "<p>Welcome to the helpdesk.</p>",
    published: true,
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: "kb_2",
    title: "Billing FAQ",
    slug: "billing-faq",
    category: "Billing",
    body: "<p>How billing works.</p>",
    published: true,
    createdAt: threeDaysAgo,
    updatedAt: threeDaysAgo,
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv_1",
    number: 1001,
    subject: "Q3 Platform Analytics Report — Action Required",
    mailboxId: "mb_support",
    customerId: "c_sarah",
    assigneeId: "u_sarah",
    status: "open",
    priority: "high",
    folder: "inbox",
    starred: true,
    labels: ["Important", "Finance"],
    tags: ["Important", "Finance"],
    followers: ["u_alex"],
    source: "email",
    createdAt: now,
    updatedAt: now,
    readBy: [],
    collision: [],
  },
  {
    id: "conv_2",
    number: 1002,
    subject: "Partnership Proposal — Neural Stack × Isotopiq Integration",
    mailboxId: "mb_sales",
    customerId: "c_marcus",
    assigneeId: "u_alex",
    status: "open",
    priority: "medium",
    folder: "inbox",
    starred: false,
    labels: ["Partnership"],
    tags: ["Partnership"],
    followers: [],
    source: "email",
    createdAt: dayAgo,
    updatedAt: dayAgo,
    readBy: [],
    collision: [],
  },
  {
    id: "conv_3",
    number: 1003,
    subject: "Figma file shared with you",
    mailboxId: "mb_support",
    customerId: "c_sarah",
    assigneeId: undefined,
    status: "closed",
    priority: "low",
    folder: "archive",
    starred: false,
    labels: ["Design"],
    tags: ["Design"],
    followers: [],
    source: "email",
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
    readBy: ["u_alex"],
    collision: [],
  },
  {
    id: "conv_4",
    number: 1004,
    subject: "Kubernetes cluster autoscaling issue",
    mailboxId: "mb_support",
    customerId: "c_sarah",
    assigneeId: "u_priya",
    status: "open",
    priority: "urgent",
    folder: "inbox",
    starred: true,
    labels: ["Engineering"],
    tags: ["Engineering"],
    followers: ["u_alex"],
    source: "email",
    createdAt: threeDaysAgo,
    updatedAt: threeDaysAgo,
    readBy: ["u_alex"],
    collision: ["u_priya"],
  },
  {
    id: "conv_5",
    number: 1005,
    subject: "[isotopiq/core] PR #847 merged",
    mailboxId: "mb_support",
    customerId: "c_sarah",
    assigneeId: undefined,
    status: "closed",
    priority: "low",
    folder: "archive",
    starred: false,
    labels: ["Engineering"],
    tags: ["Engineering"],
    followers: [],
    source: "email",
    createdAt: fourDaysAgo,
    updatedAt: fourDaysAgo,
    readBy: ["u_alex"],
    collision: [],
  },
  {
    id: "conv_6",
    number: 1006,
    subject: "Your Stripe invoice — $14,200.00 for August",
    mailboxId: "mb_billing",
    customerId: "c_stripe",
    assigneeId: "u_alex",
    status: "open",
    priority: "medium",
    folder: "inbox",
    starred: false,
    labels: ["Finance"],
    tags: ["Finance"],
    followers: [],
    source: "email",
    createdAt: fourDaysAgo,
    updatedAt: fourDaysAgo,
    readBy: ["u_alex"],
    collision: [],
  },
]

export const mockMessages: Message[] = [
  {
    id: id("msg"),
    conversationId: "conv_1",
    type: "customer",
    authorId: "c_sarah",
    authorType: "customer",
    body: "<p>Hi, I have finished compiling the Q3 analytics report. The numbers are looking strong overall but there are a few areas we should discuss before the board presentation next week.</p><p><strong>Key highlights:</strong></p><ul><li>Monthly active users up 34% QoQ</li><li>API call volume hit 2.1B (new record)</li><li>Churn rate dropped to 2.3%</li></ul><p>Can we schedule a 30-minute sync this week?</p>",
    bodyText: "Q3 report discussion",
    to: ["support@isotopiq.io"],
    cc: [],
    bcc: [],
    attachments: [],
    createdAt: now,
  },
  {
    id: id("msg"),
    conversationId: "conv_2",
    type: "customer",
    authorId: "c_marcus",
    authorType: "customer",
    body: "<p>Following up on our conversation at WebSummit. We are proposing a white-label integration with a revenue share model.</p><p>Would love to get on a call in the next two weeks.</p>",
    bodyText: "Partnership proposal",
    to: ["sales@isotopiq.io"],
    cc: [],
    bcc: [],
    attachments: [],
    createdAt: dayAgo,
  },
  {
    id: id("msg"),
    conversationId: "conv_3",
    type: "customer",
    authorId: "c_sarah",
    authorType: "customer",
    body: "<p>Lena Kim has shared a Figma file with you.</p>",
    bodyText: "Figma share",
    to: ["support@isotopiq.io"],
    cc: [],
    bcc: [],
    attachments: [],
    createdAt: twoDaysAgo,
  },
  {
    id: id("msg"),
    conversationId: "conv_4",
    type: "customer",
    authorId: "c_sarah",
    authorType: "customer",
    body: "<p>The incident is fully resolved as of 03:14 UTC. Root cause was a misconfigured HPA.</p><p>Full post-mortem attached.</p>",
    bodyText: "Kubernetes incident resolved",
    to: ["support@isotopiq.io"],
    cc: [],
    bcc: [],
    attachments: [
      {
        id: id("att"),
        name: "postmortem.pdf",
        size: 124000,
        type: "application/pdf",
        url: "#",
      },
    ],
    createdAt: threeDaysAgo,
  },
  {
    id: id("msg"),
    conversationId: "conv_5",
    type: "customer",
    authorId: "c_sarah",
    authorType: "customer",
    body: "<p>james-okafor merged pull request #847 into main.</p><p>feat: add streaming response support</p>",
    bodyText: "PR merged",
    to: ["support@isotopiq.io"],
    cc: [],
    bcc: [],
    attachments: [],
    createdAt: fourDaysAgo,
  },
  {
    id: id("msg"),
    conversationId: "conv_6",
    type: "customer",
    authorId: "c_stripe",
    authorType: "customer",
    body: "<p>Your monthly invoice is ready.</p><p><strong>Total: $14,200.00</strong></p>",
    bodyText: "Stripe invoice",
    to: ["billing@isotopiq.io"],
    cc: [],
    bcc: [],
    attachments: [
      {
        id: id("att"),
        name: "invoice.pdf",
        size: 56000,
        type: "application/pdf",
        url: "#",
      },
    ],
    createdAt: fourDaysAgo,
  },
]

export const defaultSettings: AppSettings = {
  companyName: "Isotopiq",
  defaultMailboxId: "mb_support",
  officeHours: "Mon-Fri 09:00-17:00 UTC",
  autoReply: false,
  whiteLabel: false,
  darkMode: true,
}

export const initialState = {
  currentUser: null as User | null,
  users: mockUsers,
  mailboxes: mockMailboxes,
  contacts: mockContacts,
  conversations: mockConversations,
  messages: mockMessages,
  tags: mockTags,
  savedReplies: mockSavedReplies,
  workflows: mockWorkflows,
  articles: mockArticles,
  notifications: [],
  settings: defaultSettings,
}
